
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blrbdhfzbjxxuntdulor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscmJkaGZ6Ymp4eHVudGR1bG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDc2NjgsImV4cCI6MjA2MTkyMzY2OH0.uysgm7z9t1JRr09iL_KofMHwk455XXGXMNdIeqgFJU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
